name: "Web Quality Gatekeeper"
description: "Run Playwright smoke checks, axe accessibility scans, Lighthouse performance audits, and visual regression diffs"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  url:
    description: "URL to audit"
    required: true
  config-path:
    description: "Path to config JSON file"
    required: false
    default: "configs/default.json"
  baseline-dir:
    description: "Directory for visual regression baselines"
    required: false
    default: "baselines"
  fail-on-a11y:
    description: "Fail if accessibility violations are found"
    required: false
    default: "true"
  fail-on-perf:
    description: "Fail if performance budgets are exceeded"
    required: false
    default: "true"
  fail-on-visual:
    description: "Fail if visual diffs exceed threshold"
    required: false
    default: "true"

outputs:
  status:
    description: "Overall audit status: pass or fail"
    value: ${{ steps.audit.outputs.status }}
  summary-path:
    description: "Path to the JSON summary file"
    value: ${{ steps.audit.outputs.summary-path }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts

    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install --with-deps chromium

    - name: Build
      shell: bash
      run: npm run build

    - name: Run audit
      id: audit
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_CONFIG: ${{ inputs.config-path }}
        INPUT_BASELINE: ${{ inputs.baseline-dir }}
        INPUT_A11Y: ${{ inputs.fail-on-a11y }}
        INPUT_PERF: ${{ inputs.fail-on-perf }}
        INPUT_VISUAL: ${{ inputs.fail-on-visual }}
      run: |
        ARGS=("$INPUT_URL" "--config" "$INPUT_CONFIG" "--baseline-dir" "$INPUT_BASELINE")
        [[ "$INPUT_A11Y" != "true" ]] && ARGS+=("--no-fail-on-a11y")
        [[ "$INPUT_PERF" != "true" ]] && ARGS+=("--no-fail-on-perf")
        [[ "$INPUT_VISUAL" != "true" ]] && ARGS+=("--no-fail-on-visual")
        node dist/cli.js audit "${ARGS[@]}"
        STATUS=$(node -e "const s=require('./artifacts/summary.json');console.log(s.overallStatus)")
        echo "status=$STATUS" >> "$GITHUB_OUTPUT"
        echo "summary-path=artifacts/summary.json" >> "$GITHUB_OUTPUT"
