name: Bug report
description: Report a problem with Web Quality Gatekeeper
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Output of `wqg --version` or commit SHA
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue
      placeholder: |
        1. Run ...
        2. Visit ...
        3. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Actual behavior
  - type: textarea
    attributes:
      label: Logs or artifacts
      description: Include summary.json or relevant logs if possible
