name: Feature request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe your ideal solution
  - type: textarea
    attributes:
      label: Alternatives considered
